### ISSUE TITLE
PruneCluster

### ISSUE THREAD

**Issue by nelsonlarocca** [sebnyberg/nuxt-leaflet-example#1]
> Not an issue !

Do you have any clue about making PruneCluster work with vue2-leaflet ?
Thanks for sharing ! Your vue2-leaflet solution was very clear and helped me out to go ahead !

**Comment by sebnyberg** [comment]
Sorry about the extremely late reply. I made this example quite a while back and haven't really done any related work since then. I bet you found the solution somewhere :)
